# Generated by Django 5.0.3 on 2024-03-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greencap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('goal', models.TextField()),
                ('methodology', models.TextField()),
                ('date', models.TimeField()),
                ('contact', models.TextField()),
            ],
        ),
    ]
