# Generated by Django 5.0.3 on 2024-03-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greencap',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='greencap',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='greencap',
            name='picture',
            field=models.ImageField(default='foobar', upload_to=''),
        ),
        migrations.AlterField(
            model_name='greencap',
            name='date',
            field=models.DateField(),
        ),
    ]
